/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEscanearRouteImport } from './routes/_authenticated/escanear'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedVerificarIdRouteImport } from './routes/_authenticated/verificar.$id'
import { Route as ApiPublicAgentePendientesRouteImport } from './routes/api/public/agente/pendientes'
import { Route as ApiPublicAgenteResultadoRouteImport } from './routes/api/public/agente/resultado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscanearRoute = AuthenticatedEscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificarIdRoute =
  AuthenticatedVerificarIdRouteImport.update({
    id: '/verificar/$id',
    path: '/verificar/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentePendientesRoute =
  ApiPublicAgentePendientesRouteImport.update({
    id: '/api/public/agente/pendientes',
    path: '/api/public/agente/pendientes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgenteResultadoRoute =
  ApiPublicAgenteResultadoRouteImport.update({
    id: '/api/public/agente/resultado',
    path: '/api/public/agente/resultado',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/escanear': typeof AuthenticatedEscanearRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificar/$id': typeof AuthenticatedVerificarIdRoute
  '/api/public/agente/pendientes': typeof ApiPublicAgentePendientesRoute
  '/api/public/agente/resultado': typeof ApiPublicAgenteResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/escanear': typeof AuthenticatedEscanearRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificar/$id': typeof AuthenticatedVerificarIdRoute
  '/api/public/agente/pendientes': typeof ApiPublicAgentePendientesRoute
  '/api/public/agente/resultado': typeof ApiPublicAgenteResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/escanear': typeof AuthenticatedEscanearRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/verificar/$id': typeof AuthenticatedVerificarIdRoute
  '/api/public/agente/pendientes': typeof ApiPublicAgentePendientesRoute
  '/api/public/agente/resultado': typeof ApiPublicAgenteResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/escanear'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/verificar/$id'
    | '/api/public/agente/pendientes'
    | '/api/public/agente/resultado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/escanear'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/verificar/$id'
    | '/api/public/agente/pendientes'
    | '/api/public/agente/resultado'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/escanear'
    | '/_authenticated/historial'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/verificar/$id'
    | '/api/public/agente/pendientes'
    | '/api/public/agente/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentePendientesRoute: typeof ApiPublicAgentePendientesRoute
  ApiPublicAgenteResultadoRoute: typeof ApiPublicAgenteResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escanear': {
      id: '/_authenticated/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof AuthenticatedEscanearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verificar/$id': {
      id: '/_authenticated/verificar/$id'
      path: '/verificar/$id'
      fullPath: '/verificar/$id'
      preLoaderRoute: typeof AuthenticatedVerificarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agente/pendientes': {
      id: '/api/public/agente/pendientes'
      path: '/api/public/agente/pendientes'
      fullPath: '/api/public/agente/pendientes'
      preLoaderRoute: typeof ApiPublicAgentePendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agente/resultado': {
      id: '/api/public/agente/resultado'
      path: '/api/public/agente/resultado'
      fullPath: '/api/public/agente/resultado'
      preLoaderRoute: typeof ApiPublicAgenteResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEscanearRoute: typeof AuthenticatedEscanearRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedVerificarIdRoute: typeof AuthenticatedVerificarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEscanearRoute: AuthenticatedEscanearRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedVerificarIdRoute: AuthenticatedVerificarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentePendientesRoute: ApiPublicAgentePendientesRoute,
  ApiPublicAgenteResultadoRoute: ApiPublicAgenteResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
